apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simapp
  template:
    metadata:
      labels:
        app: simapp
    spec:
      containers:
      - name: simapp
        image: simimage
        ports:
        - containerPort: 8000
