apiVersion: v1
kind: Service
metadata:
  name: {{ template "mychart.fullname" . }}
  labels:
    app: {{ template "mychart.name" . }}
    chart: {{ template "mychart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort:  {{ .Values.service.port }}
      nodePort:  {{ .Values.service.nodePort }}
      protocol: TCP
      name: http
  selector:
    app: {{ template "mychart.name" . }}
    release: {{ .Release.Name }}
